vscode:
  host: 127.0.0.1
  port: 9999
  binaryPath: third_party/openvscode-server-v1.67.0-darwin-arm64/bin/openvscode-server
  dataDir: temp/data
  workspaceDir: temp/workspace
oss:
  bucket: gdz
  dataPath: openvscode-server-data.zip
  workspacePath: openvscode-server-workspace.zip